### ISSUE TITLE
The owner of QQ group refuses to add new member 

### ISSUE THREAD

**Issue by ann61c** [Pix-00/TransBox#1]
Hi, 

I am trying to join the QQ group, but the prompt message shows that the owner refuses to add the new member. Is this on purpose or otherwise? 

Thanks
![IMG_2639](https://user-images.githubusercontent.com/3508411/116724832-b56f4180-aa13-11eb-9217-03925aad96cc.PNG)

**Comment by k3-cat** [comment]
Hi,

Thank you for contact me, but I have to say sorry about that I am not the owner of this group. 

For your question, yes, shizu has currently blocked this group and not allowed new members to join in. It was due to a pervious event that one person uses many different accounts to join this group and harass other members. 

I am not sure if this group will be open in the future, but hope it will be.

Warm regards,
Pix-00
